pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=amd64
      - check-success~=analyse \([a-z]*\)
      - check-success=build
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=unit-testing
      - check-success=zizmor
      - "#check-success>=20"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=amd64
      - check-success~=analyse \([a-z]*\)
      - check-success=build
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=unit-testing
      - check-success=zizmor
      - "#check-success>=20"
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=amd64
      - check-success~=analyse \([a-z]*\)
      - check-success=build
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=unit-testing
      - check-success=zizmor
      - "#check-success>=20"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
