name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  playwright-test-shard:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        shardIndex:
          - [1, 1]
          - [2, 2]
          - [3, 3]
          - [4, 4]
          - [5, 5]
          - [6, 6]
          - [7, 7]
          - [8, 8]
          - [9, 9]
          - [1, 10]
          - [2, 11]
          - [3, 12]
          - [4, 13]
          - [5, 14]
          - [6, 15]
          - [7, 16]
          - [8, 17]
          - [9, 18]
        shardTotal: [9]
    name: >
      test-shard (${{ matrix.shardIndex[1] <= matrix.shardTotal && 'dev' || 'prod' }}) -
      (${{ matrix.shardIndex[0] }}, ${{ matrix.shardTotal }})

    container:
      image: mcr.microsoft.com/playwright:v1.59.1@sha256:b0ab6f3cb99aa7803adbc14d9027ec1785fc6e433b97e134e0f8fe61683b6b53
      options: --user 1001
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Run Playwright tests (dev)
        if: ${{ matrix.shardIndex[1] <= matrix.shardTotal }}
        run: >
          pnpm exec playwright test
          --shard=${{ matrix.shardIndex[0] }}/${{ matrix.shardTotal }}
      - name: Run Playwright tests (prod)
        if: ${{ matrix.shardIndex[1] > matrix.shardTotal }}
        run: >
          pnpm exec playwright test
          --config playwright.prod.config.ts
          --shard=${{ matrix.shardIndex[0] }}/${{ matrix.shardTotal }}

      - name: Upload playwright report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: blob-report-${{ matrix.shardIndex[1] }}
          path: blob-report
          retention-days: 1

  playwright-tests:
    runs-on: ubuntu-24.04
    needs:
      - playwright-test-shard
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: pnpm exec playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7
