name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.62.0@sha256:baed2032d533817f3dbe6425de795788430ba345e819a1201337009ba17c9d07
      options: --user 1001
    steps:
      - name: Git Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: pnpm test --project storybook
        env:
          FORCE_COLOR: "1"
