name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.62.1@sha256:dcc5531e97840b9b5e794f2814476b21571c5124a3fca2267d73041f56e7580e
      options: --user 1001
    steps:
      - name: Git Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: pnpm test --project storybook
        env:
          FORCE_COLOR: "1"
